### ISSUE TITLE
3.0.0

### ISSUE THREAD

**Issue by eneroth** [warrant-dev/warrant-java#24]
Am I hallucinating, or is 3.0.0 not actually on Maven yet? :) 

https://mvnrepository.com/artifact/dev.warrant/warrant-java

**Comment by akajla09** [comment]
Hm.. seems like the pkg upload itself didn't go through to the mvn repos. I've gone ahead and pushed a patch `3.0.1` which should now be uploaded (might take a few mins to propagate). Can you try that and let me know if it works for you?

**Comment by eneroth** [comment]
Thank you, this worked nicely!

While I have your attention, could I ask you about https://github.com/warrant-dev/edge-agent/issues/19? 

I'm evaluating FGA solutions for our app. The data is we're dealing with is a graph, and we need to be able to resolve permissions from pretty much any point in it. 

`warrant-java`, with the tutorial setup, yields 180-190ms latency for the read permissions check given in the tutorial. I'm guessing some (most perhaps) of this is cumulative network latency (we're in Stockholm), but it also disqualifies Warrant pretty much instantly.

However, the Edge Agent looks like very good idea to bridge the network latency gap. Do you have a way in which I could evaluate this without immediately signing on with at least a mid-tier paid account?

**Comment by kkajla12** [comment]
Hi @eneroth, I responded to your [issue in the edge-agent repository](https://github.com/warrant-dev/edge-agent/issues/19). I'm closing this issue as completed and we can continue any further discussion related to the other issue in that thread.
